import { createHash, createHmac } from 'node:crypto';

/**
 * Private object storage for chat attachments (Cloudflare R2, S3-compatible API).
 *
 * The application never proxies file bytes through its own request bodies: it hands out
 * short-lived signed links for one object and one operation. Credentials live only in the
 * server environment and are never sent to the browser.
 */

export type AttachmentStorageConfig = {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
};

export type AttachmentStorageReadiness =
  | { ready: true; config: AttachmentStorageConfig }
  | { ready: false; reason: 'not_configured' | 'invalid_configuration' };

const ACCOUNT_ID = /^[a-f0-9]{32}$/;
const BUCKET = /^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/;

/** Reads the storage settings. Missing settings simply mean attachments are switched off. */
export function resolveAttachmentStorage(env: NodeJS.ProcessEnv = process.env): AttachmentStorageReadiness {
  const accountId = String(env.R2_ACCOUNT_ID || '').trim().toLowerCase();
  const accessKeyId = String(env.R2_ACCESS_KEY_ID || '').trim();
  const secretAccessKey = String(env.R2_SECRET_ACCESS_KEY || '').trim();
  const bucket = String(env.R2_ATTACHMENTS_BUCKET || '').trim();
  if (!accountId && !accessKeyId && !secretAccessKey && !bucket) return { ready: false, reason: 'not_configured' };
  if (!ACCOUNT_ID.test(accountId) || !BUCKET.test(bucket) || accessKeyId.length < 16 || secretAccessKey.length < 32) {
    return { ready: false, reason: 'invalid_configuration' };
  }
  return { ready: true, config: { accountId, accessKeyId, secretAccessKey, bucket } };
}

/** RFC 3986 encoding, as required by the signature: only A-Z a-z 0-9 - _ . ~ stay as they are. */
function encodeRfc3986(value: string) {
  return encodeURIComponent(value).replace(/[!'()*]/g, (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`);
}

function hmac(key: Buffer | string, value: string) {
  return createHmac('sha256', key).update(value, 'utf8').digest();
}

/**
 * Builds a pre-signed URL (AWS Signature Version 4, query-string form).
 * Any header given in `signedHeaders` must be sent with exactly that value, otherwise the
 * storage refuses the request. That is how an upload is pinned to one type and one size.
 */
export function presignS3Url(input: {
  method: 'GET' | 'PUT' | 'HEAD' | 'DELETE';
  host: string;
  path: string;
  accessKeyId: string;
  secretAccessKey: string;
  region: string;
  expiresSeconds: number;
  now?: Date;
  signedHeaders?: Record<string, string>;
}) {
  const now = input.now || new Date();
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, '');
  const date = amzDate.slice(0, 8);
  const scope = `${date}/${input.region}/s3/aws4_request`;
  const expires = Math.max(1, Math.min(604_800, Math.trunc(input.expiresSeconds)));

  const headers: Record<string, string> = { host: input.host };
  for (const [name, value] of Object.entries(input.signedHeaders || {})) {
    headers[name.toLowerCase()] = String(value).trim();
  }
  const headerNames = Object.keys(headers).sort();
  const signedHeaderList = headerNames.join(';');

  const query: Record<string, string> = {
    'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
    'X-Amz-Credential': `${input.accessKeyId}/${scope}`,
    'X-Amz-Date': amzDate,
    'X-Amz-Expires': String(expires),
    'X-Amz-SignedHeaders': signedHeaderList,
  };
  const canonicalQuery = Object.keys(query).sort()
    .map((name) => `${encodeRfc3986(name)}=${encodeRfc3986(query[name] ?? '')}`)
    .join('&');
  const canonicalPath = input.path.split('/').map(encodeRfc3986).join('/');
  const canonicalHeaders = headerNames.map((name) => `${name}:${headers[name] ?? ''}\n`).join('');
  const canonicalRequest = [
    input.method,
    canonicalPath,
    canonicalQuery,
    canonicalHeaders,
    signedHeaderList,
    'UNSIGNED-PAYLOAD',
  ].join('\n');
  const stringToSign = [
    'AWS4-HMAC-SHA256',
    amzDate,
    scope,
    createHash('sha256').update(canonicalRequest, 'utf8').digest('hex'),
  ].join('\n');
  const signingKey = hmac(hmac(hmac(hmac(`AWS4${input.secretAccessKey}`, date), input.region), 's3'), 'aws4_request');
  const signature = createHmac('sha256', signingKey).update(stringToSign, 'utf8').digest('hex');
  return `https://${input.host}${canonicalPath}?${canonicalQuery}&X-Amz-Signature=${signature}`;
}

/** Object keys are generated by the server and never contain anything typed by a visitor. */
export function buildAttachmentObjectKey(input: { tenantId: string; conversationId: string; attachmentId: string }) {
  const safe = (value: string) => value.replace(/[^A-Za-z0-9_-]/g, '');
  return `tenants/${safe(input.tenantId)}/conversations/${safe(input.conversationId)}/${safe(input.attachmentId)}`;
}

function objectUrl(config: AttachmentStorageConfig, input: {
  method: 'GET' | 'PUT' | 'HEAD' | 'DELETE';
  key: string;
  expiresSeconds: number;
  now?: Date;
  signedHeaders?: Record<string, string>;
}) {
  return presignS3Url({
    method: input.method,
    host: `${config.accountId}.r2.cloudflarestorage.com`,
    path: `/${config.bucket}/${input.key}`,
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    region: 'auto',
    expiresSeconds: input.expiresSeconds,
    now: input.now,
    signedHeaders: input.signedHeaders,
  });
}

/** Link the browser uses to send one file. It only accepts the declared type and exact size. */
export function createAttachmentUploadUrl(config: AttachmentStorageConfig, input: {
  key: string;
  contentType: string;
  contentLength: number;
  now?: Date;
}) {
  return objectUrl(config, {
    method: 'PUT',
    key: input.key,
    expiresSeconds: 300,
    now: input.now,
    signedHeaders: { 'content-type': input.contentType, 'content-length': String(input.contentLength) },
  });
}

/** Link a team member's browser uses to download one file. Valid for one minute. */
export function createAttachmentDownloadUrl(config: AttachmentStorageConfig, input: { key: string; now?: Date }) {
  return objectUrl(config, { method: 'GET', key: input.key, expiresSeconds: 60, now: input.now });
}

/** Reads the stored file on the server, refusing anything larger than `maxBytes`. */
export async function readAttachmentObject(config: AttachmentStorageConfig, input: {
  key: string;
  maxBytes: number;
  fetchImpl?: typeof fetch;
}) {
  const fetcher = input.fetchImpl || fetch;
  const response = await fetcher(objectUrl(config, { method: 'GET', key: input.key, expiresSeconds: 60 }), {
    method: 'GET',
    cache: 'no-store',
  });
  if (response.status === 404) return null;
  if (!response.ok) throw new Error(`attachment_storage_read_${response.status}`);
  const declared = Number(response.headers.get('content-length') || '0');
  if (declared > input.maxBytes) return null;
  const bytes = new Uint8Array(await response.arrayBuffer());
  return bytes.byteLength > input.maxBytes ? null : bytes;
}

/** Deletes one file for good. A file that is already gone counts as deleted. */
export async function deleteAttachmentObject(config: AttachmentStorageConfig, input: {
  key: string;
  fetchImpl?: typeof fetch;
}) {
  const fetcher = input.fetchImpl || fetch;
  const response = await fetcher(objectUrl(config, { method: 'DELETE', key: input.key, expiresSeconds: 60 }), {
    method: 'DELETE',
    cache: 'no-store',
  });
  if (!response.ok && response.status !== 404) throw new Error(`attachment_storage_delete_${response.status}`);
  return true;
}
